// Code generated by mockery v2.0.0. DO NOT EDIT.

package gawetest

import mock "github.com/stretchr/testify/mock"

// IdentifiableJob is an autogenerated mock type for the IdentifiableJob type
type IdentifiableJob struct {
	mock.Mock
}

// JobID provides a mock function with given fields:
func (_m *IdentifiableJob) JobID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// JobType provides a mock function with given fields:
func (_m *IdentifiableJob) JobType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Tags provides a mock function with given fields:
func (_m *IdentifiableJob) Tags() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
